### PR TITLE
Add two new loudness fields (integrated_lufs and truepeak_lufs) to VideoFile

### LINKED ISSUE #95: Database should store loudness information
We want the playout to play video with a loudness of -23 LUFS.  But the various recordings have different loundness levels, and we do not record the loudness level today.  This make it harder to adjust the loudness of the playout.

We should extend the database to store loudness level and true peak values for every video entry (or perhaps for every videofile entry), and extend the player to use this information to adjust the loudness during playout.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This allow us to measure the loudness for each file and pass this information
on to the playout to adjust the volume of the video during playout to ensure
we send with LUFS -23 according to the Norwegian TV sound level standard.

The fields are optional, because not all VideoFile entries are videos,
some are images and subtitles.

Fixes #95

### CODE REVIEW

**Comment by odinho** [comment]
I was thinking to have a JSON or Key-Value `metadata` field for this instead. That makes more sense IMHO for such extra metadata addons.

**Comment by petterreinholdtsen** [comment]
Storing it as JSON make it harder to search for videos with specific LUFS values.  Is there a way to make a Key-Value that work also for sqlite?  I've only seen it availalbe for PostgreSQL mysef.

**Comment by odinho** [comment]
Why are you searching for files with specific lufs value? And postgres can
search for that. If you make it an endpoint for sure you can do whatever
you want.

It makes it a lot easier to add useful metadata from clients.

**Comment by phed** [comment]
You don't want to search for exact float values anyway. But a range for
statistical or diagnostic purposes is useful (eg for videos that are quiet
or overly loud).

**Comment by phed** [comment]
Patch looks good to me.

**Comment by petterreinholdtsen** [comment]
I notice the xml output from bs1770gain for truepeak lufs is named tpfs, not lufs.  Perhaps our code should use that name in the model?

**Comment by petterreinholdtsen** [comment]
Discussed this with @odinho on #frikanalen and we agreed to split this pull request into smaller ones.  Pull request #147 is the first, adding some database fields and showing them to the ones updating video metadata.

**Comment by petterreinholdtsen** [comment]
I split this pull request in two (#147 and #148), and close this one.

There is still one feature missing: Measuring the loudness of the existing video archive.

**Pull request closed without merging**
