### PR TITLE
Update the UI of the clock

### PR DESCRIPTION
**Pull request by csdodd**
Trianglify is used to generate a background
The rendering of the clocks hands and hour markers has been adjusted.

Comparison image:

Screenshot 2020-11-19 at 12 49 45

### CODE REVIEW

**Comment by csdodd** [comment]
CC @toresbe 

The code scanning checks fail as part of a file I didn't touch -- this should probably be fixed in a separate PR.

**Comment by toresbe** [comment]
Wow, hello! Welcome to the project - I'm beyond thrilled to see this PR! :)

I've already been working on merging the broadcast graphics with our React frontend, in order to have more convenient access to our APIs (for programme schedules and the like).

That's currently on https://frikanalen.no/graphics ([source](https://github.com/Frikanalen/frikanalen/tree/master/packages/frontend/pages/graphics)) - but I will absolutely merge and deploy this change so it will be apparent on the currently running playout, and then adapt the code to the React frontend code.

**Comment by toresbe** [comment]
> CC @toresbe
> 
> The code scanning checks fail as part of a file I didn't touch -- this should probably be fixed in a separate PR.

You're right; I'll deal with this.

**Comment by toresbe** [comment]
Deployed. The new screen looks fantastic, thanks ever so much!

In case you might be interested in further contributions to our broadcast graphics, let me fill you in on where the project is on this:

- The playout is being refactored, and will in the near future pass the number of seconds required to be filled by the broadcast graphics as a GET parameter. This change will be relatively simultaneous with the change to the React-based graphics.

- Something - I was currently thinking React, but  if you want to do your own thing here you're more than welcome to - will then schedule various screens. Immediately I was thinking our Twitter feed, news articles (to be implemented), upcoming programmes, and this screen.

- A very ugly prototype of this is in [the frontend code base](https://github.com/Frikanalen/frikanalen/blob/master/packages/frontend/pages/graphics/index.tsx#L23) and I will be copying your changes into that code base.

Thanks again, and please don't hesitate to get in touch if contributing to any of this sounds like good fun to you.

**Comment by csdodd** [comment]
The new React frontend seems like a big improvement. I could try porting my code to the React codebase?

Do you have any ideas of how I can simulate how visual changes will look in playout on a TV set -- should I just design for 1920 x 1080?

**Comment by toresbe** [comment]
I've already ported most of it to React, albeit slightly hackishly. It'll be deployed soon today as I work to figure out some other issues. Feel free to continue tweaking this.

As it is, we're transmitting on 1280x720 - so if you design for that then we should be good. As it stands, we unfortunately don't have an easily available development playout in our own stack. But since broadcast graphics are a priority, that's absolutely something I'm working on. If you have access to a box that will run CasparCG locally, it's quite easy to make it render HTML.

For now, please just design for your browser, and I'll make any adjustments that might be needed. :)

**Comment by toresbe** [comment]
There we go! It's rolled out on https://frikanalen.no/graphics now. ^_^

Getting trianglify to build was more than a slight headache, as the node package had some dependencies with ornery builds. I just chucked in the bundled JS file for now, and hacked together a rather ugly React component, but it gets the job done for now.

**Comment by toresbe** [comment]
By the way: To avoid setting off frozen-image alerts, some sort of animation on static displays of eg. schedule is highly advantageous.

**Comment by toresbe** [comment]
The new playout has been deployed, so the React-based clock is currently used on air. :)

**Pull request merged**
