### PR TITLE
Embed tweets

### PR DESCRIPTION
**Pull request by csdodd**
The graphics code has been extended to add support for showing the latest tweet from @FriKanalen.

A URL parameter is sent to determine if the schedule or a tweet should be shown next to the analogue clock.

Sending `?style=twitter` will show the latest tweet, anything else will revert to showing the schedule.

Screenshot 2020-11-30 at 15 08 33

### CODE REVIEW

**Comment by csdodd** [comment]
CC @toresbe 

It is not possible to style the way the tweet renders since I am using a library that just ends up generating an iFrame. If we want to have more control over the look of the tweet we will have to build something ourselves that pulls the latest tweet.

**Comment by toresbe** [comment]
Thanks for this PR! I'll make some adaptations for this to be in line with my idea for how this page is to work.

Basically, the playout passes the number of milliseconds and the idea is that Index is to fill that time intelligently (eg. if there are only five seconds, all of it is used on "Next up...", if there's more time, add the Twitter feed, etc.)

**Comment by toresbe** [comment]
The iframe issue seems to be inherent to using Twitter without the API - and the API requires authentication. I've applied for an API account at Twitter, and will hack something together once it is approved.

**Comment by toresbe** [comment]
Ugh... the Twitter API is terrible. I've been banging my head against the problem of getting tweet data and it's just not worth it. I'll make some adaptations to this PR before merging, though.

**Comment by toresbe** [comment]
Thanks for the PR! I really appreciate the work!

**Comment by toresbe** [comment]
For the record, I've ended up with this:

https://simula.frikanalen.no/~toresbe/fk-grafikk-program.png
https://simula.frikanalen.no/~toresbe/fk-grafikk-nyheter.png

**Pull request merged**
