### PR TITLE
Redirect GET requests from /upload to /.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This make it easier to understand why the upload URL is not responding to GET.

### CODE REVIEW

**Comment by odinho** [comment]
Not sure this is useful.

We could/should even remove the front-page. It could just be a simple "This is an upload endpoint for frikanalen. You probably want to use the webui at frikanalen.no/" text, and that could be returned on GET  for `/upload` and also on `/`.

The upload.html that's there doesn't work anymore since we require a correct code for uploading.

**Comment by petterreinholdtsen** [comment]
[Odin Hørthe Omdal]
> Not sure this is useful.

It would have helped me a lot when trying to figure out how to use the
upload URL. :)

> We could/should even remove the front-page. It could just be a simple
> "This is an upload endpoint for frikanalen. You probably want to use
> the webui at frikanalen.no/" text, and that could be returned on GET
> for `/upload` and also on `/`.

Redirecting to a page with information about the process and pointers to
the source would have been useful to me, at least, instead of the
'method not working' message I get today.

> The upload.html that's there doesn't work anymore since we require a
> correct code for uploading.

Right.  I guess it could ask for video ID and fetch it. :)

My priority at the moment is a command line uploader, so I can script
video uploads.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by odinho** [comment]
> It would have helped me a lot when trying to figure out how to use the
upload URL. :)

Yes, but so would just printing the equivalent text as JSON without doing a redirect, right? Or actually just saying what it needs even more so.

**Comment by odinho** [comment]
I have done the change I suggested instead at https://github.com/Frikanalen/frikanalen/commit/61c783dd9defe2836ca5da647d4357e30449bdf5#diff-6c28c33547877a012c5f9a2e400e1048L35

**Pull request closed without merging**
